Repository Hack-Weekly/onyx-sal-blog, pull requests merged in 2023-04, with the labels that each got.

#25 About page
  client/.env
  client/src/Layout.jsx
  client/src/components/About/index.css
  client/src/components/About/index.js
  client/src/components/Footer/index.css
  client/src/components/Footer/index.js
  client/src/components/Metrics/index.js
  client/src/index.css
  client/src/pages/About.jsx
  client/src/pages/Metrics.jsx
Labels: effort: 1, priority: soon

#38 Add Backend
  client/src/dummyData.js
  client/src/pages/Blog.jsx
  server/.gitignore
  server/.prettierrc
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/src/index.ts
  server/src/prisma.ts
  server/src/routes/posts.ts
  server/src/routes/tags.ts
  server/tsconfig.json
Labels: effort: 8, priority: soon, backend

#47 Add Comments Table and Left Join Author Information
  server/prisma/schema.prisma
  server/src/routes/posts.ts
  server/src/routes/tags.ts
Labels: backend

#48 Pull blog posts api
  client/package-lock.json
  client/package.json
  client/src/dummyData.js
  client/src/pages/Blog.jsx
Labels: frontend

#55 GitHub oauth backend crap
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/src/index.ts
  server/src/routes/github.ts
  server/src/routes/posts.ts
  server/src/services/githubServices.ts
  server/src/types/AccessTokenData.ts
  server/src/types/GitHubUser.ts
Labels: backend, authorization

#60 Add login and fix small bugs
  client/package-lock.json
  client/package.json
  client/src/Layout.css
  client/src/Layout.jsx
  client/src/index.css
  client/src/stores/userStore.js
  client/src/utils/gitHubServices.js
  server/prisma/schema.prisma
  server/src/index.ts
  server/src/routes/posts.ts
  server/src/routes/users.ts
  server/src/services/githubServices.ts
Labels: frontend, backend, authorization

#64 Add admin crap
  server/prisma/schema.prisma
  server/src/routes/posts.ts
  server/src/routes/users.ts
  server/src/services/githubServices.ts
Labels: backend, authorization

#65 Formatting balooza
  client/src/App.js
  client/src/Layout.css
  client/src/Layout.jsx
  client/src/components/singleBlogPost/index.css
  client/src/components/singleBlogPost/index.jsx
  client/src/pages/Blog.jsx
Labels: effort: 14, frontend, authorization
